// Generated by gencpp from file centauro_locomotion_msgs/TerrainClassMap.msg
// DO NOT EDIT!


#ifndef CENTAURO_LOCOMOTION_MSGS_MESSAGE_TERRAINCLASSMAP_H
#define CENTAURO_LOCOMOTION_MSGS_MESSAGE_TERRAINCLASSMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace centauro_locomotion_msgs
{
template <class ContainerAllocator>
struct TerrainClassMap_
{
  typedef TerrainClassMap_<ContainerAllocator> Type;

  TerrainClassMap_()
    : header()
    , num_cells_x(0)
    , num_cells_y(0)
    , origin_x(0.0)
    , origin_y(0.0)
    , resolution(0.0)
    , terrain_class()  {
    }
  TerrainClassMap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_cells_x(0)
    , num_cells_y(0)
    , origin_x(0.0)
    , origin_y(0.0)
    , resolution(0.0)
    , terrain_class(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _num_cells_x_type;
  _num_cells_x_type num_cells_x;

   typedef uint32_t _num_cells_y_type;
  _num_cells_y_type num_cells_y;

   typedef float _origin_x_type;
  _origin_x_type origin_x;

   typedef float _origin_y_type;
  _origin_y_type origin_y;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _terrain_class_type;
  _terrain_class_type terrain_class;




  typedef boost::shared_ptr< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> const> ConstPtr;

}; // struct TerrainClassMap_

typedef ::centauro_locomotion_msgs::TerrainClassMap_<std::allocator<void> > TerrainClassMap;

typedef boost::shared_ptr< ::centauro_locomotion_msgs::TerrainClassMap > TerrainClassMapPtr;
typedef boost::shared_ptr< ::centauro_locomotion_msgs::TerrainClassMap const> TerrainClassMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace centauro_locomotion_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'centauro_locomotion_msgs': ['/home/xi/workspace/terrain_classifier/preprocessor/src/centauro_locomotion_msgs/msg', '/home/xi/workspace/terrain_classifier/preprocessor/devel/share/centauro_locomotion_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680c0bea5d8ebb060be0a31a74be2125";
  }

  static const char* value(const ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680c0bea5d8ebb06ULL;
  static const uint64_t static_value2 = 0x0be0a31a74be2125ULL;
};

template<class ContainerAllocator>
struct DataType< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "centauro_locomotion_msgs/TerrainClassMap";
  }

  static const char* value(const ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# terrain classes from visual terrain classification\n\
# 0 = free\n\
# 1 = rough\n\
# 2 = obstacle\n\
# 3 = stairs\n\
# 4 = narrow section\n\
\n\
Header header\n\
\n\
# Size in cells\n\
uint32 num_cells_x\n\
uint32 num_cells_y\n\
\n\
# Cell coordinates of (0,0)\n\
float32 origin_x\n\
float32 origin_y\n\
\n\
# Resolution (m / cell)\n\
float32 resolution\n\
\n\
# Height values per cell (row step: cells_x)\n\
uint32[] terrain_class\n\
 \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_cells_x);
      stream.next(m.num_cells_y);
      stream.next(m.origin_x);
      stream.next(m.origin_y);
      stream.next(m.resolution);
      stream.next(m.terrain_class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TerrainClassMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::centauro_locomotion_msgs::TerrainClassMap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_cells_x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_cells_x);
    s << indent << "num_cells_y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_cells_y);
    s << indent << "origin_x: ";
    Printer<float>::stream(s, indent + "  ", v.origin_x);
    s << indent << "origin_y: ";
    Printer<float>::stream(s, indent + "  ", v.origin_y);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "terrain_class[]" << std::endl;
    for (size_t i = 0; i < v.terrain_class.size(); ++i)
    {
      s << indent << "  terrain_class[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.terrain_class[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTAURO_LOCOMOTION_MSGS_MESSAGE_TERRAINCLASSMAP_H
