(cl:defpackage centauro_locomotion_msgs-msg
  (:use )
  (:export
   "<DRIVINGMOVEMENT>"
   "DRIVINGMOVEMENT"
   "<TERRAINCLASSMAP>"
   "TERRAINCLASSMAP"
   "<LEGMOVEMENTRESULT>"
   "LEGMOVEMENTRESULT"
   "<LEGMOVEMENTFEEDBACK>"
   "LEGMOVEMENTFEEDBACK"
   "<LEGMOVEMENTACTIONRESULT>"
   "LEGMOVEMENTACTIONRESULT"
   "<LEGMOVEMENTACTION>"
   "LEGMOVEMENTACTION"
   "<LEGMOVEMENTACTIONGOAL>"
   "LEGMOVEMENTACTIONGOAL"
   "<LEGMOVEMENTACTIONFEEDBACK>"
   "LEGMOVEMENTACTIONFEEDBACK"
   "<LEGMOVEMENTGOAL>"
   "LEGMOVEMENTGOAL"
  ))

