; Auto-generated. Do not edit!


(cl:in-package centauro_locomotion_msgs-msg)


;//! \htmlinclude LegMovementFeedback.msg.html

(cl:defclass <LegMovementFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LegMovementFeedback (<LegMovementFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LegMovementFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LegMovementFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name centauro_locomotion_msgs-msg:<LegMovementFeedback> is deprecated: use centauro_locomotion_msgs-msg:LegMovementFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LegMovementFeedback>) ostream)
  "Serializes a message object of type '<LegMovementFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LegMovementFeedback>) istream)
  "Deserializes a message object of type '<LegMovementFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LegMovementFeedback>)))
  "Returns string type for a message object of type '<LegMovementFeedback>"
  "centauro_locomotion_msgs/LegMovementFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LegMovementFeedback)))
  "Returns string type for a message object of type 'LegMovementFeedback"
  "centauro_locomotion_msgs/LegMovementFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LegMovementFeedback>)))
  "Returns md5sum for a message object of type '<LegMovementFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LegMovementFeedback)))
  "Returns md5sum for a message object of type 'LegMovementFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LegMovementFeedback>)))
  "Returns full string definition for message of type '<LegMovementFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LegMovementFeedback)))
  "Returns full string definition for message of type 'LegMovementFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LegMovementFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LegMovementFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LegMovementFeedback
))
