// Generated by gencpp from file centauro_locomotion_msgs/DrivingMovement.msg
// DO NOT EDIT!


#ifndef CENTAURO_LOCOMOTION_MSGS_MESSAGE_DRIVINGMOVEMENT_H
#define CENTAURO_LOCOMOTION_MSGS_MESSAGE_DRIVINGMOVEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace centauro_locomotion_msgs
{
template <class ContainerAllocator>
struct DrivingMovement_
{
  typedef DrivingMovement_<ContainerAllocator> Type;

  DrivingMovement_()
    : header()
    , vel_x(0.0)
    , vel_y(0.0)
    , omega(0.0)  {
    }
  DrivingMovement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vel_x(0.0)
    , vel_y(0.0)
    , omega(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _vel_x_type;
  _vel_x_type vel_x;

   typedef float _vel_y_type;
  _vel_y_type vel_y;

   typedef float _omega_type;
  _omega_type omega;




  typedef boost::shared_ptr< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> const> ConstPtr;

}; // struct DrivingMovement_

typedef ::centauro_locomotion_msgs::DrivingMovement_<std::allocator<void> > DrivingMovement;

typedef boost::shared_ptr< ::centauro_locomotion_msgs::DrivingMovement > DrivingMovementPtr;
typedef boost::shared_ptr< ::centauro_locomotion_msgs::DrivingMovement const> DrivingMovementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace centauro_locomotion_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'centauro_locomotion_msgs': ['/home/xi/workspace/terrain_classifier/preprocessor/src/centauro_locomotion_msgs/msg', '/home/xi/workspace/terrain_classifier/preprocessor/devel/share/centauro_locomotion_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb3f3ba37e2319ebb04ef8305faf22f9";
  }

  static const char* value(const ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb3f3ba37e2319ebULL;
  static const uint64_t static_value2 = 0xb04ef8305faf22f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "centauro_locomotion_msgs/DrivingMovement";
  }

  static const char* value(const ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the desired robot center driving movement in longitudinal direction (x), \n\
# lateral direction (y) and around the z_axis (omega). Leg configurations are fixed. \n\
# This message will arrive in a rate between 20 and 50 Hz. If some delay occurs due to\n\
# steering wheels in the required direction, this is no problem.\n\
\n\
Header header\n\
\n\
float32 vel_x\n\
float32 vel_y\n\
float32 omega\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vel_x);
      stream.next(m.vel_y);
      stream.next(m.omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrivingMovement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::centauro_locomotion_msgs::DrivingMovement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vel_x: ";
    Printer<float>::stream(s, indent + "  ", v.vel_x);
    s << indent << "vel_y: ";
    Printer<float>::stream(s, indent + "  ", v.vel_y);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CENTAURO_LOCOMOTION_MSGS_MESSAGE_DRIVINGMOVEMENT_H
