// Generated by gencpp from file centauro_locomotion_msgs/LegMovementResult.msg
// DO NOT EDIT!


#ifndef CENTAURO_LOCOMOTION_MSGS_MESSAGE_LEGMOVEMENTRESULT_H
#define CENTAURO_LOCOMOTION_MSGS_MESSAGE_LEGMOVEMENTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace centauro_locomotion_msgs
{
template <class ContainerAllocator>
struct LegMovementResult_
{
  typedef LegMovementResult_<ContainerAllocator> Type;

  LegMovementResult_()
    {
    }
  LegMovementResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> const> ConstPtr;

}; // struct LegMovementResult_

typedef ::centauro_locomotion_msgs::LegMovementResult_<std::allocator<void> > LegMovementResult;

typedef boost::shared_ptr< ::centauro_locomotion_msgs::LegMovementResult > LegMovementResultPtr;
typedef boost::shared_ptr< ::centauro_locomotion_msgs::LegMovementResult const> LegMovementResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace centauro_locomotion_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'centauro_locomotion_msgs': ['/home/xi/workspace/terrain_classifier/preprocessor/src/centauro_locomotion_msgs/msg', '/home/xi/workspace/terrain_classifier/preprocessor/devel/share/centauro_locomotion_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "centauro_locomotion_msgs/LegMovementResult";
  }

  static const char* value(const ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result:\n\
";
  }

  static const char* value(const ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegMovementResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::centauro_locomotion_msgs::LegMovementResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CENTAURO_LOCOMOTION_MSGS_MESSAGE_LEGMOVEMENTRESULT_H
