(cl:in-package centauro_locomotion_msgs-msg)
(cl:export '(GOAL_POS_FL_X-VAL
          GOAL_POS_FL_X
          GOAL_POS_FL_Y-VAL
          GOAL_POS_FL_Y
          GOAL_POS_FL_Z-VAL
          GOAL_POS_FL_Z
          WHEEL_ROTATION_ENABLED_FL-VAL
          WHEEL_ROTATION_ENABLED_FL
          GOAL_POS_BL_X-VAL
          GOAL_POS_BL_X
          GOAL_POS_BL_Y-VAL
          GOAL_POS_BL_Y
          GOAL_POS_BL_Z-VAL
          GOAL_POS_BL_Z
          WHEEL_ROTATION_ENABLED_BL-VAL
          WHEEL_ROTATION_ENABLED_BL
          GOAL_POS_BR_X-VAL
          GOAL_POS_BR_X
          GOAL_POS_BR_Y-VAL
          GOAL_POS_BR_Y
          GOAL_POS_BR_Z-VAL
          GOAL_POS_BR_Z
          WHEEL_ROTATION_ENABLED_BR-VAL
          WHEEL_ROTATION_ENABLED_BR
          GOAL_POS_FR_X-VAL
          GOAL_POS_FR_X
          GOAL_POS_FR_Y-VAL
          GOAL_POS_FR_Y
          GOAL_POS_FR_Z-VAL
          GOAL_POS_FR_Z
          WHEEL_ROTATION_ENABLED_FR-VAL
          WHEEL_ROTATION_ENABLED_FR
))