; Auto-generated. Do not edit!


(cl:in-package centauro_locomotion_msgs-msg)


;//! \htmlinclude LegMovementResult.msg.html

(cl:defclass <LegMovementResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LegMovementResult (<LegMovementResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LegMovementResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LegMovementResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name centauro_locomotion_msgs-msg:<LegMovementResult> is deprecated: use centauro_locomotion_msgs-msg:LegMovementResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LegMovementResult>) ostream)
  "Serializes a message object of type '<LegMovementResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LegMovementResult>) istream)
  "Deserializes a message object of type '<LegMovementResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LegMovementResult>)))
  "Returns string type for a message object of type '<LegMovementResult>"
  "centauro_locomotion_msgs/LegMovementResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LegMovementResult)))
  "Returns string type for a message object of type 'LegMovementResult"
  "centauro_locomotion_msgs/LegMovementResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LegMovementResult>)))
  "Returns md5sum for a message object of type '<LegMovementResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LegMovementResult)))
  "Returns md5sum for a message object of type 'LegMovementResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LegMovementResult>)))
  "Returns full string definition for message of type '<LegMovementResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result:~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LegMovementResult)))
  "Returns full string definition for message of type 'LegMovementResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result:~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LegMovementResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LegMovementResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LegMovementResult
))
